orbs:
  node: circleci/node@4.1.0

version: 2.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 14.15.0
      - node/test:
          version: 12.16.0
      - node/test:
          version: 10.19.0
